# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: createrepo_c.spec

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-all
  - job: tests
    trigger: pull_request
    identifier: "createrepo_c-tests"
    targets:
      - fedora-all
    fmf_url: https://github.com/rpm-software-management/ci-dnf-stack.git
    fmf_ref: enable-tmt-dnf-4-stack
    tmt_plan: "^/plans/integration/behave-createrepo_c$"

