# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: createrepo_c.spec

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-all
